title: Dagmawi Fasil # your name (or website title) here
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  Hi! Welcome to my Github Portoflio. I hope you enojoy reading my insights as much as I enojyed scraping and analyzing data across the web.
  <br><br>
  I'm currently a Data Scientst at Bowery Farming
  I have 5 years of data analytics experience ranging across financial services, ad tech and media/entertainment industries.
  <br><br>
  If you want to reach out, feel free to contact me at my LinkedIn Profile Below
  <br><br>
  <a href="https://www.linkedin.com/in/dagmawi-fasil-241205100/" target="_blank" rel="noopener noreferrer">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-E0KH6EBCSS # your Google Analytics tracking ID here
